/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.gametrack;

import controller.GameTrackController;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.entity.GameTrack;

/**
 *
 * @author juanito
 */
public class GameTrackViewImpl extends javax.swing.JPanel implements GameTrackView {

    private GameTrackController controller;
    
    private GameTrackTableModel gameTrackTableModel;
    private GameTrackViewImplInternal gameTrackPanelInternal;
    
    /**
     * Creates new form GameTrackViewImpl
     */
    public GameTrackViewImpl() {
        this.gameTrackTableModel = new GameTrackTableModel();
        initComponents();
        this.gameTrackPanelInternal = new GameTrackViewImplInternal(this);
        this.gameTrackPanel.add(this.gameTrackPanelInternal);
        
        // listens to selection changes in table
        this.trackTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    int selectedRow = trackTable.getSelectedRow();
                    if (selectedRow != -1) {
                        GameTrack selectedTrack = gameTrackTableModel.getRow(selectedRow);
                        gameTrackPanelInternal.loadSelectedTrack(selectedTrack);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trackTable = new javax.swing.JTable();
        gameTrackPanel = new javax.swing.JPanel();

        trackTable.setModel(gameTrackTableModel);
        jScrollPane1.setViewportView(trackTable);

        gameTrackPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gameTrackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameTrackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public GameTrackController getController() {
        return controller;
    }

    @Override
    public void setController(GameTrackController controller) {
        this.controller = controller;
    }

    @Override
    public void dataModelChanged() {
        gameTrackTableModel.setTracks(this.getController().listTracksGesture());
    }
    
    @Override
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dataModelChanged();
            }
        });
    }
    
    public void fireSetTrackGesture(String userId, String gameId, String platformId, String progress, String playedHours){
        this.controller.setTrackGesture(userId, gameId, platformId, progress, playedHours);
    }
    
    public String getSelectedTrackId(){
        int selectedRow = this.trackTable.getSelectedRow();
        
        // no row selected
        if(selectedRow == -1){
            return null;
        }
        
        GameTrack selectedTrack = this.gameTrackTableModel.getTracks().get(selectedRow);
        
        return String.valueOf(selectedTrack.getId());
    }
    
    public void fireUpdateTrackGesture(String id, String userId, String gameId, String platformId, String progress, String playedHours){
        this.controller.updateTrackGesture(id, userId, gameId, platformId, progress, playedHours);
    }
    
    // not implemented yet
    public void fireDeleteTrackGesture(String id){
        this.controller.deleteTrackGesture(id);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameTrackPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trackTable;
    // End of variables declaration//GEN-END:variables
}
