/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.game;

import controller.GameController;
import model.entity.Game;

/**
 *
 * @author juanito
 */
public class GameViewImpl extends javax.swing.JPanel implements GameView {

    
    private GameController controller;
    
    private GameTableModel gameTableModel;
    private GameViewImplInternal gamePanelInternal;
    
    /**
     * Creates new form GameViewImpl
     */
    public GameViewImpl() {
        this.gameTableModel = new GameTableModel();
        initComponents();
        this.gamePanelInternal = new GameViewImplInternal(this);
        this.gamePanel.add(this.gamePanelInternal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gameTable = new javax.swing.JTable();
        gamePanel = new javax.swing.JPanel();

        gameTable.setModel(gameTableModel);
        jScrollPane1.setViewportView(gameTable);

        gamePanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public GameController getController() {
        return controller;
    }

    @Override
    public void setController(GameController controller) {
        this.controller = controller;
    }

    @Override
    public void dataModelChanged() {
        gameTableModel.setGames(this.getController().listGamesGesture());
    }
    
    @Override
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                dataModelChanged();
            }
        });
    }
    
    public void fireSetGameGesture(String title, String studio, String launchYear){
        this.getController().setGameGesture(title, studio, launchYear);
    }
    
    public String getSelectedGameId(){
        int selectedRow = this.gameTable.getSelectedRow();
        
        // no row selected
        if(selectedRow == -1){
            return null;
        }
        
        Game selectedGame = this.gameTableModel.getGames().get(selectedRow);
        
        return String.valueOf(selectedGame.getId());
    }
    
    public void fireUpdateGameGesture(String id, String title, String studio, String launchYear){
        this.getController().updateGameGesture(id, title, studio, launchYear);
    }
    
    public void fireDeleteGameGesture(String id, String title, String studio, String launchYear){
        this.getController().deleteGameGesture(id, title, studio, launchYear);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gamePanel;
    private javax.swing.JTable gameTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
