/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.user;

import controller.UserController;
import model.entity.User;

/**
 *
 * @author juanito
 */
public class UserViewImpl extends javax.swing.JPanel implements UserView {

    private UserController controller;
    
    // swing attributes
    private UserTableModel userTableModel;
    private UserViewImplInternal userPanelInternal;
    
    /**
     * Creates new form UserViewImpl
     */
    public UserViewImpl() {
        userTableModel = new UserTableModel();
        initComponents();
        this.userPanelInternal = new UserViewImplInternal(this);
        this.userPanel.add(this.userPanelInternal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        userPanel = new javax.swing.JPanel();

        usersTable.setModel(userTableModel);
        jScrollPane1.setViewportView(usersTable);

        userPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public UserController getController() {
        return controller;
    }

    @Override
    public void setController(UserController controller) {
        this.controller = controller;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dataModelChanged() {
        userTableModel.setUsers(this.getController().listUsersGesture());
    }
    
    @Override
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dataModelChanged();
            }
        });
    }
    
    public void fireSetUserGesture(String username, String email){
        this.getController().setUserGesture(username, email);
    }
    
    public String getSelectedUserId(){
        int selectedRow = this.usersTable.getSelectedRow();
        
        // no row selected
        if(selectedRow == -1){
            return null;
        }
        
        User selectedUser = this.userTableModel.getUsers().get(selectedRow);
        
        return String.valueOf(selectedUser.getId());
    }
    
    public void fireUpdateUserGesture(String id, String username, String email){
        this.getController().updateUserGesture(id, username, email);
    }
    
    public void fireDeleteUserGesture(String id, String username, String email){
        this.getController().deleteUserGesture(id, username, email);
    }
}
